### ISSUE TITLE
 Directive to create the source code for your projects

### ISSUE THREAD

**Issue by ghost** [mailchimp/style-guide#13]
I read the style guide with great interest. I think that the programmers have a style guide to create the source code. Is it possible this also to publish?

**Comment by jordanandree** [comment]
Hey @joergklein 

the developer (@TheRealAlan) who built the style guide just posted a blog post on how we built the style guide. Check it out here: http://devs.mailchimp.com/blog/how-we-built-the-mailchimp-content-style-guide/

Feel free to comment on that blog post if you have questions.
