### ISSUE TITLE
Broken parenthetical commas in grammar section

### ISSUE THREAD

**Issue by robclewley** [mailchimp/style-guide#14]
In the Grammar and Mechanics section, under the Slang and Jargon subsection, the following sentence has an unmatched parenthetical comma.

> "One way we do this is with shards, or partitions that help us better horizontally scale our database infrastructure."

I believe it should be written:

> "One way we do this is with shards, or partitions, that help us better horizontally scale our database infrastructure."

**Comment by stevenosloan** [comment]
thanks @robclewley!
