### ISSUE TITLE
Nitpicky Issue with Grammar and Mechanics

### ISSUE THREAD

**Issue by krempshaw** [mailchimp/style-guide#16]
This is regarding the specifics of the style guide rather than it's implementation using Markdown, so I'm hoping this is the still the right place to submit this.

First, I must say that I really appreciate this. My organization is is desperate need of a style guide, so I'm adapting much of yours for a first draft. 

Specifically, I'm concerned about the section on Time. It's stated that time should be written with a space between digits and am or pm, but when time is written as a span of time, there are no spaces. Is this an oversight or intentional? 

7am-10:20pm vs 7 am-10:30 pm

The second looks better to my eyes, but I also feel kind of silly pointing this out. I guess. 

Thanks for your time in making this, it's very helpful

**Comment by stevenosloan** [comment]
Hey @krempshaw, thanks for caring enough about words to worry about things like this 😄. I checked in with one of our writers to get a bit more info -- here's their response:

> It was intentional, though we don't expect everyone to agree with every part of our guide. Go with what makes sense for you!
