### ISSUE TITLE
Resources Link broken on "Creating Structured Content" page

### ISSUE THREAD

**Issue by damenleeturks** [mailchimp/style-guide#19]
On the "Creating Structured Content" page/chapter, the link for the "Resources" page is missing/broken:  

- broken link on the [live site](https://styleguide.mailchimp.com/creating-structured-content/): https://styleguide.mailchimp.com/resources
- broken link as referenced within [this repo](https://github.com/mailchimp/content-style-guide/blob/master/14-creating-structured-content.html.md): https://github.com/mailchimp/content-style-guide/blob/master/18-resources.html.md

**Comment by damenleeturks** [comment]
Ditto with the template link further down on the page: https://styleguide.mailchimp.com/resources/template-elements

**Comment by damenleeturks** [comment]
Any updates here, guys?

**Comment by br00kehatfield** [comment]
Hey @damenleeturks! We’ve removed those broken links.
