### ISSUE TITLE
In "Writing About People"

### ISSUE THREAD

**Issue by Toad945** [mailchimp/style-guide#21]
Hiya, Awesome MailChimp People!

First off, you all are wonderful!  Thank you so much for this resource! 

I edit a great blog by an #ActuallyAutistic SLP (speech language pathologist) whose clients are all littles on the spectrum.  I am also in the same category (#ActuallyAutistic, not an SLP).  As such, you might want to be aware that many, many of us *detest* person-first language.  Some of us find it wonderful.  But I've not met many of the latter.  As a person with 'mental illness,' I can tell you the same rules apply as with other 'disabilities'.  No matter who it is, or the thing they have limitations around - these same rules apply. 

So, here are some thoughts on writing about people from the 'disabled' person's perspective:

It's best to *check* with the person you are writing about to find out *how they prefer to be described.* and then describe them that way consistently.  Do not just use a style guide's instruction, which will cause you to ignore the actual person's needs and will damage your relationship with both that individual and their entire community.  Yes, we do talk to each other and if your presentation of us in an interview goes against what we told you we were comfortable with to satisfy a style guide over a human being - we probably won't ever listen you, trust you, or read your work again.  And we will tell others why.  

For example, I am autistic. Not a person with autism.  Saying I am a person with autism is as absurd as saying I'm a person with a brain, as though the brain (without which I will die) is somehow separate from me.  I hope this helps clarify what person-first language sounds like to some of us out there reading blogs.

Always check with your subject as to how they want to be presented. It shows to your readers that you are really about that good relationship with them.  It fosters trust in your blog, and your character. And you may find yourself on the receiving end of good press for your actual allyship to others, rather than for caving to the opinions of people who don't actually live the issues your blog is discussing.

In closing, I am beyond grateful for your hard work, folks!  I hope you are not irritated by my comment here, but I want your principles, as stated in the intro, to really be felt by those who use your products.  And this tiny change (advising to consult with your subject as to how they wish to be presented - person first or in some other manner) would prove to your minority readers and users that you MEAN EXACTLY WHAT YOU WROTE. 

Thank you!   Toad945

**Comment by br00kehatfield** [comment]
Hey @Toad945 ! Thank you so much for your thoughtful feedback. We heard the same thing from some of our employees. We’ve updated Writing About People to reflect that writers should ask subjects whether they prefer person-first or identity-first language when their disability is relevant to copy.
