### ISSUE TITLE
Blog post link is broken in README

### ISSUE THREAD

**Issue by gaurav-nelson** [mailchimp/style-guide#39]
The link to the blog post redirects to `https://mailchimp.com/developer/` instead of `http://devs.mailchimp.com/blog/how-we-built-the-mailchimp-content-style-guide/`

**Comment by jordanandree** [comment]
Thanks for the heads up! 
This was removed with 8b5e3af21d766ad3238d5e7a7bf2009ee645dd43 since that content has since been retired.
