### ISSUE TITLE
Question - how are you displaying the pages on your website?

### ISSUE THREAD

**Issue by danyork** [mailchimp/style-guide#8]
Hi!  Thanks for: 1) writing this guide; 2) writing it all in Markdown so it is easy to edit;  and 3) making it available under a CC license!  It's quite an excellent guide!

This isn't an "issue" as much as a question - how are you creating the actual web pages that appear at http://styleguide.mailchimp.com/ ?

Are you running the set of md files through something to create HTML files?  Are you using a web server that translates md files to HTML on the fly?  Or doing something completely different?

I think it's great that you have the section at the end of `CONTRIBUTING.md` about 'Creating Your Own Style Guide", but I feel like this piece about putting the style guide pages on your own website is missing.  If you could add something there - or perhaps point to a blog post where you explain how you did it - that would be very helpful for people who might want to adapt the guide.

Many thanks again for writing this and making it available!
Dan

**Comment by jordanandree** [comment]
We use [Middleman](https://middlemanapp.com/), a static site generator to build the web version. it handles the routing of Markdown files into HTML. We source this repo into the web version via a [git submodule](https://git-scm.com/docs/git-submodule).

That's a really overly simple explanation of how we are building the web version, so a more blog post is something we should totally do.

**Comment by mdamjanic7** [comment]
That blog post would be awesome :)

**Comment by davidmartinez** [comment]
@danyork yes! I was wondering the same thing. 
@jordanandree thank you for the answer, I assume Middleman is a set files that can be loaded and executed on a web hosting service, I'll read into it more
@mdamjanic7 agreed - a blog post would be amazing.

**Comment by davidmartinez** [comment]
Is there any way to download the content that's already been converted into static HTML output? I'd like to start a project from there (http://styleguide.mailchimp.com/)...

**Comment by jordanandree** [comment]
Hey everyone,

A blog post was just published on Engineering blog that should give you all an overview of how we built the site that displays this content (thanks to the @TheRealAlan): http://devs.mailchimp.com/blog/how-we-built-the-mailchimp-content-style-guide/

Feel free to post some feedback over on that post. Going to close this issue out.
